# Common information for the Github workflow.
name: Continuous Integration
run-name: Continuous Integration on "${{ github.ref_name }}" by "@${{ github.actor }}"

# This workflow has the following configuration:
# - It's possible to trigger it manually.
# - It does NOT run on the `main` branch.
# - It does run when a `push` is made when it contain changes to `.sln`, `.cs` or `.csproj` file(s).
# - It does run when a PR is `opened`, `reopened` or synchronized` and when it contain changes to
#   `.sln`, `.cs` or `.csproj` file(s).
on:
  workflow_dispatch:
  push:
    branches:
      - '!main'
    paths:
      - '**.sln'
      - '**.cs'
      - '**.csproj'
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths:
      - '**.sln'
      - '**.cs'
      - '**.csproj'

# Define the entire workflow.
jobs:
  build-and-test:
    name: Build & Test NuGet packages on "${{ matrix.os }}" using ".NET ${{ matrix.dotnet-version }}"
    concurrency: testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        # os: [ ubuntu-latest, windows-latest, macOS-latest ]
        dotnet-version: [ '7.0.202' ]
    steps:
      - name: GIT Clone
        uses: actions/checkout@v3

      - name: Setup ".NET ${{ matrix.dotnet-version }}"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore NuGet packages (dotnet restore)
        working-directory: app
        run: dotnet restore

      - name: Build .NET Solution (dotnet build)
        working-directory: app
        run: dotnet build --no-incremental --no-restore /p:CIBuild=true

      - name: Run tests
        uses: zyborg/dotnet-tests-report@v1.4.4
        with:
          project_path: app/CHILI.UVault.sln
          no_restore: true
          no_build: true
          report_name: CHILI UVault (Quality Report)
          github_token: ${{ secrets.GITHUB_TOKEN }}
          set_check_status_from_test_outcome: true`
          fail_build_on_failed_tests: true
